

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/devops-task.crt;
    ssl_certificate_key /etc/nginx/ssl/devops-task.key;

    root /var/www/devops-site;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /health {
        try_files /health.html =404;
    }

}