server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate {{CERT}};
    ssl_certificate_key {{KEY}};
    root {{ROOT}};

    index index.html;

    access_log /var/log/nginx/devops-site-ssl.access.log;
    error_log /var/log/nginx/devops-site-ssl.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
